openapi: 3.0.1
info:
  title: WSO2-API
  description: API Definition of WSO2-API
  version: 1.0.0
servers:
- url: http://localhost:8290/healthcare
paths:
  /querydoctor/{category}:
    get:
      parameters:
      - name: category
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
